# Installation de la suite LAMP 
- hosts: 192.168.56.104
  tasks:
    - name: "installation de la suite lamp"
      become: yes
      become_user: root
      yum:
        pkg:
          - httpd
          - mariadb-server
          - php
          - php-mysql
        state: present
        update_cache: yes

    - name: "demarrage du service apache"
      become: yes
      become_user: root
      service:
        name: httpd
        state: started
        enabled: yes

    - name: "demarrage du service mysql"
      become: yes
      become_user: root
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: "bypass creation du dossier html et 755 dessus"
      file: path=/var/www/html state=directory mode=0755

    - name: "copie des fichiers de app-salaire dans le dossier du site principal" 
      become: yes
      become_user: root
      copy:
        src: /app-salaire/
        dest: /var/www/html

